name: Uptime Monitoring

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  uptime:
    runs-on: ubuntu-latest
    steps:
      - name: Check website status
        uses: lissy93/uptime-kuma@v1
        with:
          url: 'https://focuslab.io'
          push-url: '${{ secrets.UPTIME_KUMA_PUSH_URL }}' 