name: Uptime Monitoring

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  uptime:
    runs-on: ubuntu-latest
    steps:
      - name: Check website status
        run: |
          echo "Checking website uptime..."
          response=$(curl -s -o /dev/null -w "%{http_code}" https://focuslab.io)
          if [ $response -eq 200 ]; then
            echo "✅ Website is up (HTTP $response)"
          else
            echo "❌ Website is down (HTTP $response)"
            exit 1
          fi 